max_width = 80
hard_tabs = false
tab_spaces = 8
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2024"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
group_imports = "StdExternalCrate"
# normalize_comments = true
# wrap_comments = true
